<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Delete Company 1.1</name>
   <tag></tag>
   <elementGuidId>192cf5a6-2b8a-4af9-bc7b-c5c6a5c6ef3a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzNDgyMTMxOTQxMTk3NzQwNTk5YWI1ZiIsImdvb2dsZUlkIjoiMTA2Mjc2MDYyMjUyNjMyNDY5NTMxIiwiZW1haWwiOiJpdHVpbmlpbmlpdHUxM0BnbWFpbC5jb20iLCJmdWxsTmFtZSI6ImluaSBpdHUiLCJwaG90b1VybCI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FMbTV3dTJ4bG83dFZoY3pDWjVaaWdfTlRHNzhKcVFxbXpxU1ItMGlSQXY1PXM5Ni1jIiwiYmlvIjoiIiwic3RhdHVzIjoiIiwiY3JlYXRlZEF0IjoiMjAyMi0xMC0xM1QxNDozMToxMy4wMzZaIiwidXBkYXRlZEF0IjoiMjAyMy0wMS0wNVQxNzo0NTowMS4yOTBaIiwiX192IjowLCJkZWZhdWx0Q29tcGFueSI6bnVsbH0sImlhdCI6MTY3MzAyNTE3MywiZXhwIjoxNjc1NjE3MTczfQ.5RiuxaXFjmFViJW0xfjE3l5_iecYXc8opzrxjvMD5YQ</value>
      <webElementGuid>375c7b56-fe9a-4d86-b003-5f910f443028</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>7f1b2df0-ef05-4613-9c3a-8af96a77ca84</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>7.5.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>DELETE</restRequestMethod>
   <restUrl>${baseURL}/api/v1/companies/63bbc8dabab253e23339b303</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.baseURL</defaultValue>
      <description></description>
      <id>38f3cf94-44f4-4763-bab8-0ef9cd0e2d4d</id>
      <masked>false</masked>
      <name>baseURL</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
